### ISSUE TITLE
I get "Directory does not exist"

### ISSUE THREAD

**Issue by anacierdem** [social13/line-counter-node#2]
I get a "Directory does not exist" when doing;

`linecounter --path "/home/chronos/user/Downloads/reconfigure"`

on ChromeOS (I doubt it is chrome OS related)

**Comment by osenekci** [comment]
Equals character is required to define parameters. It should be like following linecounter --path="/home/chronos/user/Downloads/reconfigure"

**Comment by anacierdem** [comment]
That explains it, ty.
